{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0972bdb4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "def load_and_clean_data():\n",
    "    # 1. Load original NASA weather data\n",
    "    weather = pd.read_csv(\"https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv\",\n",
    "                          skiprows=1,\n",
    "                          na_values=\"***\")\n",
    "\n",
    "    # 2. Select year and month columns\n",
    "    month_columns = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',\n",
    "                     'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']\n",
    "    weather_selected = weather[['Year'] + month_columns].copy()\n",
    "\n",
    "    # 3. Melt from wide to long format\n",
    "    tidyweather = weather_selected.melt(id_vars=['Year'],\n",
    "                                        value_vars=month_columns,\n",
    "                                        var_name='month',\n",
    "                                        value_name='delta')\n",
    "\n",
    "    # 4. Convert year & month to datetime objects\n",
    "    tidyweather['date'] = pd.to_datetime(tidyweather['Year'].astype(str) + '-' + tidyweather['month'] + '-01',\n",
    "                                         format='%Y-%b-%d',\n",
    "                                         errors='coerce')\n",
    "    tidyweather['month_name'] = tidyweather['date'].dt.strftime('%b')\n",
    "    tidyweather['year'] = tidyweather['date'].dt.year\n",
    "    \n",
    "    # Drop rows with missing delta or date (as in the faceted plot step of the notebook)\n",
    "    tidyweather = tidyweather.dropna(subset=['delta', 'date'])\n",
    "\n",
    "    # 5. Create comparison dataframe with time intervals\n",
    "    comparison = tidyweather[tidyweather['Year'] >= 1881].copy()\n",
    "\n",
    "    def get_interval(year):\n",
    "        if 1881 <= year <= 1920:\n",
    "            return \"1881-1920\"\n",
    "        elif 1921 <= year <= 1950:\n",
    "            return \"1921-1950\"\n",
    "        elif 1951 <= year <= 1980:\n",
    "            return \"1951-1980\"\n",
    "        elif 1981 <= year <= 2010:\n",
    "            return \"1981-2010\"\n",
    "        else:\n",
    "            return \"2011-present\"\n",
    "\n",
    "    comparison['interval'] = comparison['Year'].apply(get_interval)\n",
    "    comparison['interval'] = pd.Categorical(comparison['interval'],\n",
    "                                            categories=['1881-1920', '1921-1950', '1951-1980',\n",
    "                                                        '1981-2010', '2011-present'],\n",
    "                                            ordered=True)\n",
    "\n",
    "    return tidyweather, comparison"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
